name: czech
description: A starting point for Dart libraries or applications.
version: 0.0.1
author:
  - Darius Kryszczuk <darius.kryszczuk@gmail.com>
  -

environment:
  sdk: '>=1.20.1 <2.0.0'

dev_dependencies:
  test: ^0.12.0
