name: czech
description: Set of Czechia-specific functions.
version: 1.0.0
homepage: https://github.com/fnx-io/czech
authors:
  - Darius Kryszczuk <darius.kryszczuk@gmail.com>
  - Tomas Zverina <tomucha@gmail.com>

environment:
  sdk: '>=2.0.0-dev.61.0 <3.0.0'

dev_dependencies:
  test: ^1.3.0
