name: czech
description: Set of Czechia-specific functions.
version: 0.1.2
homepage: https://github.com/fnx-io/czech
authors:
  - Darius Kryszczuk <darius.kryszczuk@gmail.com>
  - Tomas Zverina <tomucha@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dev_dependencies:
  test: ^0.12.0
